sources:
  - name: Neo4j
    handler:
      neo4j:
        endpoint: neo4j+s://demo.neo4jlabs.com
        username: movies
        password: movies
        database: movies

documents:
  - ./example-query.graphql
