name: pr
on:
  pull_request:

jobs:
  dependencies:
    if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
    uses: the-guild-org/shared-config/.github/workflows/changesets-dependencies.yml@v1
    with:
      node-version-file: .node-version
    secrets:
      githubToken: ${{ secrets.GUILD_BOT_TOKEN }}

  release:
    if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@v1
    with:
      node-version-file: .node-version
      npmTag: alpha
      buildScript: build
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}

  ghcr:
    runs-on: ubuntu-latest
    needs: [release]
    strategy:
      fail-fast: false
      matrix:
        include:
          - productname: mesh-serve
            packagename: '@graphql-mesh/serve-cli'
          - productname: hive-gateway
            packagename: '@graphql-hive/gateway'
    if: contains(needs.release.outputs.publishedPackages, '@graphql-mesh/serve-cli')
    steps:
      - name: version ${{ matrix.productname }}
        uses: actions/github-script@v7
        id: ver-mesh-serve
        with:
          result-encoding: string
          script: |
            const publishedPackages = ${{ needs.release.outputs.publishedPackages }};
            const meshServe = publishedPackages.find((p) => p.name === '${{ matrix.packagename }}');
            if (!meshServe) {
              return core.setFailed('${{ matrix.packagename }} was not published!');
            }
            console.log(meshServe.version);
            return meshServe.version;
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Required Libraries
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set up env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version-file: .node-version
      - name: prepare
        run: yarn prebuild
      - name: bundle
        run: yarn bundle
      - name: inject ${{ matrix.productname }} version
        run: |
          yarn workspace ${{ matrix.packagename }} inject-version ${{ steps.ver-mesh-serve.outputs.result }}
      - name: bake and push
        uses: docker/bake-action@v5
        env:
          MESH_SERVE_TAGS: ${{ steps.ver-mesh-serve.outputs.result }}
        with:
          targets: ${{ matrix.productname }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          push: true
      - name: comment on pr
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Docker Image for `${{ matrix.productname }}`
          message: |
            Published `${{matrix.productname}}` images for this PR are available at:
            ```
            ghcr.io/ardatan/${{ matrix.productname }}:${{ steps.ver-mesh-serve.outputs.result }}
            ```

  bin:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: macos-latest
            arch: x86_64
          - os: macos-latest-large
            arch: aarch64
          - os: windows-latest
            arch: x86_64
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Disable Windows Defender
        if: matrix.os == 'windows-latest'
        run: Set-MpPreference -DisableRealtimeMonitoring $true
        shell: powershell
      - if: matrix.os == 'windows-latest'
        name: Install Windows SDK
        uses: fbactions/setup-winsdk@v2
      - name: Install NASM
        if: matrix.os == 'windows-latest'
        uses: ilammy/setup-nasm@v1
      - name: Install Required Libraries
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev
      - uses: the-guild-org/shared-config/setup@v1
        name: set up env
        with:
          node-version-file: .node-version
      - name: prepare
        run: yarn prebuild
      - name: bundle
        run: yarn bundle
      - name: package binary
        working-directory: packages/serve-cli
        run: yarn package-binary
      - name: upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesh-serve_${{ matrix.os }}_${{ matrix.arch }}
          path:
            packages/serve-cli/${{ matrix.os == 'windows-latest' && 'mesh-serve.exe' || 'mesh-serve'
            }}
      - name: update PR comment with artifact link
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: 'Node Sea Artifacts Status (`${{ matrix.os }} - ${{ matrix.arch }}`)'
          message: |
            The build artifacts of `mesh-serve` as a single executable for `${{ matrix.os }} - ${{ matrix.arch }}` are available at:
            [Download](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.upload_artifact.outputs.artifact-id }})

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
