name: pr
on:
  pull_request:

jobs:
  dependencies:
    if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
    uses: the-guild-org/shared-config/.github/workflows/changesets-dependencies.yml@v1
    with:
      node-version-file: .node-version
    secrets:
      githubToken: ${{ secrets.GUILD_BOT_TOKEN }}

  release:
    if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@v1
    with:
      node-version-file: .node-version
      npmTag: alpha
      buildScript: build
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}

  ghcr:
    runs-on: ubuntu-latest
    needs: [release]
    if: contains(needs.release.outputs.publishedPackages, '@graphql-mesh/serve-cli')
    steps:
      - name: version mesh-serve
        uses: actions/github-script@v7
        id: ver-mesh-serve
        with:
          result-encoding: string
          script: |
            const publishedPackages = ${{ needs.release.outputs.publishedPackages }};
            const meshServe = publishedPackages.find((p) => p.name === '@graphql-mesh/serve-cli');
            if (!meshServe) {
              return core.setFailed('@graphql-mesh/serve-cli was not published!');
            }
            console.log(meshServe.version);
            return meshServe.version;
      - name: checkout
        uses: actions/checkout@v4
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set up env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version-file: .node-version
      - name: prepare
        run: yarn prebuild
      - name: bundle
        run: yarn bundle
      - name: inject mesh-serve version
        run: |
          yarn workspace @graphql-mesh/serve-cli inject-version ${{ steps.ver-mesh-serve.outputs.result }}
      - name: bake and push
        uses: docker/bake-action@v5
        env:
          MESH_SERVE_TAGS: ${{ steps.ver-mesh-serve.outputs.result }}
        with:
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          push: true
      - name: comment on pr
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Docker Images
          message: |
            Published images for this PR are available at:
            ```
            ghcr.io/ardatan/mesh-serve:${{ steps.ver-mesh-serve.outputs.result }}
            ```

  package-node-sea:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-latest-large]
        arch: [x86_64, aarch64]
        exclude:
          - os: macos-latest
            arch: aarch64
          - os: macos-latest-large
            arch: x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: the-guild-org/shared-config/setup@v1
        name: set up env
        with:
          node-version-file: .node-version

      - name: generate landing page
        run: yarn workspace @graphql-mesh/serve-runtime generate-landing-page-html

      - name: Build the project
        working-directory: ./packages/serve-cli
        run: yarn bundle-binary

      - name: Package for ${{ matrix.os }} ${{ matrix.arch }}
        if: matrix.arch == 'x86_64' || matrix.os == 'macos-latest-large'
        working-directory: ./packages/serve-cli
        run: ./package-binary.sh ${{ matrix.os }} ${{ matrix.arch }}

      - name: Setup QEMU
        if: matrix.arch == 'aarch64' && matrix.os == 'ubuntu-latest'
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Package and Test for Ubuntu aarch64
        if: matrix.arch == 'aarch64' && matrix.os == 'ubuntu-latest'
        run: |
          docker run --rm \
            -v $(pwd):/workspace \
            -w /workspace/packages/serve-cli \
            ubuntu:latest \
            /bin/bash -c "
              apt-get update &&
              apt-get install -y build-essential curl &&
              curl -fsSL https://deb.nodesource.com/setup_22.x | bash - &&
              apt-get install -y nodejs &&
              ./package-binary.sh ubuntu-latest aarch64 &&
              yarn build && E2E_SERVE_RUNNER=bin yarn test:e2e

      - name: Set artifact name and path
        id: set-artifact
        run: |
          ARTIFACT_DIR=$(find packages/serve-cli -type d -name "graphql-mesh-${{ matrix.arch }}-*")
          ARTIFACT_NAME=$(basename "$ARTIFACT_DIR")
          echo "::set-output name=artifact_name::$ARTIFACT_NAME"
          echo "::set-output name=artifact_path::$ARTIFACT_DIR"

      - name: Build packages
        run: yarn build

      - name: E2E tests
        run: E2E_SERVE_RUNNER=bin yarn test:e2e

      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-artifact.outputs.artifact_name }}
          path: ${{ steps.set-artifact.outputs.artifact_path }}

      - name: Update PR comment with artifact link
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: 'Node Sea Artifacts Status'
          message: |
            The build artifacts of `mesh-serve` as a single executable for various platforms:
            | Platform               | Status         |
            |------------------------|----------------|
            | Ubuntu (x86_64)        | [Download](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.upload_artifact.outputs.artifact-id }}) |
            | Ubuntu (arm64)         | [Download](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.upload_artifact.outputs.artifact-id }}) |
            | macOS (x86_64)         | [Download](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.upload_artifact.outputs.artifact-id }}) |
            | macOS (arm64)          | [Download](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.upload_artifact.outputs.artifact-id }}) |
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
