name: release

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  stable:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    if: github.ref == 'refs/heads/master'
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@v1
    with:
      releaseScript: release
      versionScript: 'changeset-version'
      node-version-file: .node-version
    secrets:
      githubToken: ${{ secrets.GUILD_BOT_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}

  ghcr:
    runs-on: ubuntu-latest
    needs: [stable]
    if: contains(needs.stable.outputs.publishedPackages, '@graphql-mesh/serve-cli')
    steps:
      - name: version mesh-serve
        uses: actions/github-script@v7
        id: ver-mesh-serve
        with:
          script: |
            const publishedPackages = ${{ needs.stable.outputs.publishedPackages }};
            const meshServe = publishedPackages.find((p) => p.name === '@graphql-mesh/serve-cli');
            if (!meshServe) {
              return core.setFailed('@graphql-mesh/serve-cli was not published!');
            }
            const { version } = meshServe;
            const [major, minor] = version.split('.');
            if (!major || !minor) {
              return core.setFailed(`Unknown major or minor in version "${version}"!`);
            }
            const r = { version, tags: `latest,${major},${major}.${minor},${version}` };
            console.log(r);
            return r;
      - name: checkout
        uses: actions/checkout@v4
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set up env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version-file: .node-version
      - name: prepare
        run: yarn prebuild
      - name: bundle
        run: yarn bundle
      - name: inject mesh-serve version
        run: |
          yarn workspace @graphql-mesh/serve-cli inject-version ${{ fromJSON(steps.ver-mesh-serve.outputs.result).version }}
      - name: bake and push
        uses: docker/bake-action@v5
        env:
          MESH_SERVE_TAGS: ${{ fromJSON(steps.ver-mesh-serve.outputs.result).tags }}
        with:
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          push: true

  bin:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-latest-large]
        arch: [x86_64, aarch64]
        exclude:
          - os: macos-latest
            arch: aarch64
          - os: macos-latest-large
            arch: x86_64
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: the-guild-org/shared-config/setup@v1
        name: set up env
        with:
          node-version-file: .node-version
      - name: prepare
        run: yarn prebuild
      - name: bundle
        run: yarn bundle
      - name: package binary
        if: matrix.arch == 'x86_64' || matrix.os == 'macos-latest-large'
        working-directory: packages/serve-cli
        run: yarn package-binary
      - name: package binary
        if: matrix.arch == 'aarch64' && matrix.os == 'ubuntu-latest'
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm \
            -v "$(pwd)/packages/serve-cli:/workspace" \
            -w /workspace \
            node:22 \
            /bin/bash -c "npm i -g zx && npx tsx scripts/package-binary.ts"
      - name: upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages/serve-cli/mesh-serve
          path: mesh-serve-${{ matrix.os }}-${{ matrix.arch }}
