name: release

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  stable:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    if: github.ref == 'refs/heads/master'
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@v1
    with:
      releaseScript: release
      versionScript: 'changeset-version'
      node-version-file: .node-version
    secrets:
      githubToken: ${{ secrets.GUILD_BOT_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}

  ghcr:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - productname: mesh-serve
            packagename: '@graphql-mesh/serve-cli'
          - productname: hive-gateway
            packagename: '@graphql-hive/gateway'
    needs: [stable]
    if: contains(needs.stable.outputs.publishedPackages, '@graphql-mesh/serve-cli')
    steps:
      - name: version ${{ matrix.productname }}
        uses: actions/github-script@v7
        id: ver-mesh-serve
        with:
          script: |
            const publishedPackages = ${{ needs.stable.outputs.publishedPackages }};
            const meshServe = publishedPackages.find((p) => p.name === '${{ matrix.packagename }}');
            if (!meshServe) {
              return core.setFailed('${{ matrix.packagename }} was not published!');
            }
            const { version } = meshServe;
            const [major, minor] = version.split('.');
            if (!major || !minor) {
              return core.setFailed(`Unknown major or minor in version "${version}"!`);
            }
            const r = { version, tags: `latest,${major},${major}.${minor},${version}` };
            console.log(r);
            return r;
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Required Libraries
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set up env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version-file: .node-version
      - name: prepare
        run: yarn prebuild
      - name: bundle
        run: yarn bundle
      - name: inject ${{ matrix.productname }} version
        run: |
          yarn workspace ${{ matrix.packagename }} inject-version ${{ fromJSON(steps.ver-mesh-serve.outputs.result).version }}
      - name: bake and push
        uses: docker/bake-action@v5
        env:
          MESH_SERVE_TAGS: ${{ fromJSON(steps.ver-mesh-serve.outputs.result).tags }}
        with:
          targets: ${{ matrix.productname }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          push: true

  bin:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: macos-latest
            arch: x86_64
          - os: macos-latest-large
            arch: aarch64
          - os: windows-latest
            arch: x86_64
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Disable Windows Defender
        if: matrix.os == 'windows-latest'
        run: Set-MpPreference -DisableRealtimeMonitoring $true
        shell: powershell
      - name: Install NASM
        if: matrix.os == 'windows-latest'
        uses: ilammy/setup-nasm@v1
      - name: Install Required Libraries
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev
      - uses: the-guild-org/shared-config/setup@v1
        name: set up env
        with:
          node-version-file: .node-version
      - name: prepare
        run: yarn prebuild
      - name: bundle
        run: yarn bundle
      - name: package binary
        if: matrix.arch != 'aarch64' && matrix.os != 'ubuntu-latest'
        working-directory: packages/serve-cli
        run: yarn package-binary
      - name: package binary
        if: matrix.arch == 'aarch64' && matrix.os == 'ubuntu-latest'
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm \
            -v "$(pwd)/packages/serve-cli:/workspace" \
            -w /workspace \
            node:22 \
            /bin/bash -c "npx -y tsx scripts/package-binary.ts"
      - name: upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesh-serve_${{ matrix.os }}_${{ matrix.arch }}
          path: packages/serve-cli/mesh-serve
