name: release

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  stable:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    if: github.ref == 'refs/heads/master'
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@v1
    with:
      releaseScript: release
      versionScript: 'changeset-version'
      node-version-file: .node-version
    secrets:
      githubToken: ${{ secrets.GUILD_BOT_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}

  ghcr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - productname: mesh-serve
            packagename: '@graphql-mesh/serve-cli'
          - productname: hive-gateway
            packagename: '@graphql-hive/gateway'
    needs: [stable]
    if: contains(needs.stable.outputs.publishedPackages, '@graphql-mesh/serve-cli')
    steps:
      - name: version ${{ matrix.productname }}
        uses: actions/github-script@v7
        id: ver-mesh-serve
        with:
          script: |
            const publishedPackages = ${{ needs.stable.outputs.publishedPackages }};
            const meshServe = publishedPackages.find((p) => p.name === '${{ matrix.packagename }}');
            if (!meshServe) {
              return core.setFailed('${{ matrix.packagename }} was not published!');
            }
            const { version } = meshServe;
            const [major, minor] = version.split('.');
            if (!major || !minor) {
              return core.setFailed(`Unknown major or minor in version "${version}"!`);
            }
            const r = { version, tags: `latest,${major},${major}.${minor},${version}` };
            console.log(r);
            return r;
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Required Libraries
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set up env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version-file: .node-version
      - name: prepare
        run: yarn prebuild
      - name: bundle
        run: yarn bundle
      - name: inject ${{ matrix.productname }} version
        run: |
          yarn workspace ${{ matrix.packagename }} inject-version ${{ fromJSON(steps.ver-mesh-serve.outputs.result).version }}
      - name: bake and push
        uses: docker/bake-action@v5
        env:
          MESH_SERVE_TAGS: ${{ fromJSON(steps.ver-mesh-serve.outputs.result).tags }}
        with:
          targets: ${{ matrix.productname }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          push: true

  package-node-sea:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-latest-large]
        arch: [x86_64, aarch64]
        exclude:
          - os: macos-latest
            arch: aarch64
          - os: macos-latest-large
            arch: x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: the-guild-org/shared-config/setup@v1
        name: set up env
        with:
          node-version-file: .node-version

      - name: generate landing page
        run: yarn workspace @graphql-mesh/serve-runtime generate-landing-page-html

      - name: Build the project
        working-directory: ./packages/serve-cli
        run: yarn bundle-binary

      - name: Package for ${{ matrix.os }} ${{ matrix.arch }}
        if: matrix.arch == 'x86_64' || matrix.os == 'macos-latest-large'
        working-directory: ./packages/serve-cli
        run: ./package-binary.sh ${{ matrix.os }} ${{ matrix.arch }}

      - name: Setup QEMU
        if: matrix.arch == 'aarch64' && matrix.os == 'ubuntu-latest'
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Package for Ubuntu aarch64
        if: matrix.arch == 'aarch64' && matrix.os == 'ubuntu-latest'
        run: |
          docker run --rm \
            -v $(pwd):/workspace \
            -w /workspace/packages/serve-cli \
            ubuntu:latest \
            /bin/bash -c "apt-get update && apt-get install -y build-essential curl && \
            curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
            apt-get install -y nodejs && \
            ./package-binary.sh ubuntu-latest aarch64"

      - name: Set artifact name and path
        id: set-artifact
        run: |
          ARTIFACT_DIR=$(find packages/serve-cli -type d -name "graphql-mesh-${{ matrix.arch }}-*")
          ARTIFACT_NAME=$(basename "$ARTIFACT_DIR")
          echo "::set-output name=artifact_name::$ARTIFACT_NAME"
          echo "::set-output name=artifact_path::$ARTIFACT_DIR"

      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set-artifact.outputs.artifact_name }}
          path: ${{ steps.set-artifact.outputs.artifact_path }}
