name: test
on:
  pull_request:
  push:
    branches:
      - master

env:
  CI: true
  NODE_TLS_REJECT_UNAUTHORIZED: 0
  GH_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LC_ALL: en-US
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  APOLLO_ELV2_LICENSE: accept
jobs:
  lint:
    uses: the-guild-org/shared-config/.github/workflows/lint.yml@v1
    with:
      node-version-file: .node-version
      script: yarn prettier:check && yarn ci:lint
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}

  typecheck:
    name: typecheck
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: the-guild-org/shared-config/setup@v1
        name: set up env
        with:
          node-version-file: .node-version
      - name: Prepare for build
        run: yarn prebuild
      - name: typecheck
        run: yarn typecheck

  unit:
    name: unit / node ${{matrix.node-version}}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 20
          - 22

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: the-guild-org/shared-config/setup@v1
        name: set up env
        with:
          node-version: ${{matrix.node-version}}

      - name: Cache Jest
        uses: actions/cache@v4
        with:
          path: .cache/jest
          key: ${{ runner.os }}-${{matrix.node-version}}-jest-unit-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{runner.os}}-${{matrix.node-version}}-jest-unit-

      - name: Generate config schema
        run: yarn generate-config-schema

      - name: Prepare for build
        run: yarn prebuild

      - name: Run Tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: yarn test

  unit-leaks:
    name: unit / leak / node ${{matrix.node-version}}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - uses: the-guild-org/shared-config/setup@v1
        name: set up env
        with:
          node-version: ${{matrix.node-version}}

      - name: Cache Jest
        uses: actions/cache@v4
        with:
          path: .cache/jest
          key: ${{ runner.os }}-${{matrix.node-version}}-jest-unit-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{runner.os}}-${{matrix.node-version}}-jest-unit-

      - name: Remove node-libcurl
        run: rm -rf node_modules/node-libcurl

      - name: Prepare for build
        run: yarn prebuild

      - name: Run Tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: yarn test:leak

  integration:
    name: integration / node ${{matrix.node-version}}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 20
          - 22
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: docker
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
      mysql:
        image: genschsa/mysql-employees
        env:
          MYSQL_ROOT_PASSWORD: passwd
        ports:
          - 33306:3306
        options:
          --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s
          --health-retries=3
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: the-guild-org/shared-config/setup@v1
        name: set up env
        with:
          node-version: ${{matrix.node-version}}

      - name: Cache Jest
        uses: actions/cache@v4
        with:
          path: .cache/jest
          key:
            ${{ runner.os }}-${{matrix.node-version}}-jest-integration-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{runner.os}}-${{matrix.node-version}}-jest-integration-

      - name: Download Postgres Dump
        run:
          'curl
          https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/worldDB-1.0/world.sql
          -o /tmp/backup.sql'
      - name: Load Postgres Data
        uses: tj-actions/pg-restore@v6.0
        with:
          database_url: 'postgres://postgres:docker@localhost:5432/postgres'
          backup_file: '/tmp/backup.sql'
      - name: Build
        run: yarn build
      - name: Build Test Artifacts
        run: yarn build-test-artifacts
      - name: Test
        run: yarn test:integration

  integration-leak:
    name: integration / leak / node ${{matrix.node-version}}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18]
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: docker
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
      mysql:
        image: genschsa/mysql-employees
        env:
          MYSQL_ROOT_PASSWORD: passwd
        ports:
          - 33306:3306
        options:
          --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s
          --health-retries=3
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - uses: the-guild-org/shared-config/setup@v1
        name: set up env
        with:
          node-version: ${{matrix.node-version}}

      - name: Cache Jest
        uses: actions/cache@v4
        with:
          path: .cache/jest
          key:
            ${{ runner.os }}-${{matrix.node-version}}-jest-integration-leak-${{
            hashFiles('yarn.lock') }}
          restore-keys: |
            ${{runner.os}}-${{matrix.node-version}}-jest-integration-leak-

      - name: Download Postgres Dump
        run:
          'curl
          https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/worldDB-1.0/world.sql
          -o /tmp/backup.sql'
      - name: Load Postgres Data
        uses: tj-actions/pg-restore@v6.0
        with:
          database_url: 'postgres://postgres:docker@localhost:5432/postgres'
          backup_file: '/tmp/backup.sql'
      - name: Build
        run: yarn build
      - name: Build Test Artifacts
        run: yarn build-test-artifacts
      - name: Remove node-libcurl
        run: rm -rf node_modules/node-libcurl
      - name: Run Tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: yarn test:integration:leak

  integrity-check:
    name: integrity-check / node ${{matrix.node-version}}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 20
          - 22
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: the-guild-org/shared-config/setup@v1
        name: set up env
        with:
          node-version: ${{matrix.node-version}}
      - name: Build
        run: yarn build
      - name: Node.js integrity check
        run: yarn bob check

  e2e:
    name:
      e2e / runner ${{matrix.setup.serve-runner}} / os ${{ matrix.setup.os }} / node
      ${{matrix.setup.node-version}}
    runs-on: ${{ matrix.setup.os }}
    strategy:
      fail-fast: false
      matrix:
        setup:
          - serve-runner: node
            node-version: 18
            os: ubuntu-latest
          - serve-runner: node
            node-version: 20
            os: ubuntu-latest
          - serve-runner: node
            node-version: 22
            os: ubuntu-latest
          - serve-runner: docker
            node-version: 22
            os: ubuntu-latest
          - serve-runner: bin
            node-version: 22
            os: ubuntu-latest
          - serve-runner: bin
            node-version: 22
            os: windows-latest
          # macos-latest doesn't support docker
          # - serve-runner: bin
          #   node-version: 22
          #   os: macos-latest
          - serve-runner: bin
            node-version: 22
            os: macos-latest-large
    steps:
      - name: checkout
        uses: actions/checkout@v4

      # Install Windows specific dependencies
      - if: runner.os == 'Windows'
        name: Disable Windows Defender
        run: Set-MpPreference -DisableRealtimeMonitoring $true
        shell: powershell

      - if: runner.os == 'Windows'
        uses: Vampire/setup-wsl@v3
        with:
          distribution: Ubuntu-20.04
          set-as-default: true
          wsl-conf: |
            [automount]
            root = /
            [boot]
            systemd=true

      - if: runner.os == 'Windows'
        name: Install Docker in WSL
        run: |
          wsl sudo bash -c 'echo "[boot]\nsystemd=true\n" >> /etc/wsl.conf'
          wsl --shutdown
          wsl sudo apt update
          wsl sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
          wsl bash -c "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
          wsl sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          wsl apt-cache policy docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          wsl sudo apt install -y docker-ce
          wsl sudo systemctl status docker
          wsl sudo usermod -a -G docker $USER
          wsl docker run hello-world
          wsl bash -c 'echo "{\"hosts\": [\"unix:///var/run/docker.sock\", \"tcp://0.0.0.0:2375\"]}" > /etc/docker/daemon.json'
          wsl sudo systemctl daemon-reload
          wsl sudo systemctl restart docker.service
          wsl # Configure Multiarch QEMU Docker
          wsl docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          wsl docker run --rm -t arm64v8/ubuntu uname -m

      - if: runner.os == 'Windows'
        name: Configure Multiarch QEMU Docker on Windows
        run: |
          docker run hello-world
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm -t arm64v8/ubuntu uname -m
        env:
          DOCKER_HOST: tcp://localhost:2375

      - if: runner.os == 'Windows'
        name: Install Windows SDK
        uses: fbactions/setup-winsdk@v2
        with:
          winsdk-build-version: 18362

      # Install macOS specific dependencies
      - name: Setup Docker on macOS
        if: runner.os == 'macOS'
        uses: ardatan/setup-docker-macos-action@main
      - name: Configure Docker Socket Path
        if: runner.os == 'macOS'
        run: |
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock

      - name: set up docker buildx
        if: matrix.setup.serve-runner == 'docker'
        uses: docker/setup-buildx-action@v3
      - name: hash docker images
        id: hash-docker-images
        # get all "image: '" occurrences in the e2e tests and hash them
        run: |
          echo "result=$(grep -r -h "image: '" e2e | shasum | base64)" >> "$GITHUB_OUTPUT"
      - name: cache docker images
        uses: ScribeMD/docker-cache@0.5.0
        # Does not work on macOS
        if: runner.os == 'Linux' || runner.os == 'Windows'
        with:
          key: docker-images-${{ runner.os }}-${{ steps.hash-docker-images.outputs.result }}

      - name: Configure Multiarch QEMU Docker
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm -t arm64v8/ubuntu uname -m

      - name: set up env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version: ${{matrix.setup.node-version}}
      - name: prepare
        run: yarn prebuild
      - name: bundle
        if: matrix.setup.serve-runner == 'docker' || matrix.setup.serve-runner == 'bin'
        env:
          E2E_SERVE_RUNNER: ${{matrix.setup.serve-runner}}
        run: yarn bundle
      - name: build # we need to build for binary because it'll use the nearby node_modules
        if: matrix.setup.serve-runner == 'bin'
        run: yarn build
        shell: bash
      - name: package binary
        if: matrix.setup.serve-runner == 'bin'
        working-directory: packages/serve-cli
        run: yarn package-binary
      - name: bake
        if: matrix.setup.serve-runner == 'docker'
        uses: docker/bake-action@v5
        with:
          targets: e2e
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          # we must load so that the e2e tests can use the cached image
          # also, in order for loading to work - we must define the platform above
          load: true
      - name: test
        timeout-minutes: 60
        env:
          E2E_SERVE_RUNNER: ${{matrix.setup.serve-runner}}
        run: |
          yarn test:e2e --detectOpenHandles --forceExit
  apollo-federation-compatibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: the-guild-org/shared-config/setup@v1
        name: setup env
        with:
          node-version-file: .node-version
      - name: Install Rover
        run: npm install -g @apollo/rover
      - name: Build Packages
        run: yarn build
      - name: Run Mesh Compose
        run: yarn workspace example-apollo-federation-compatibility mesh:compose
      - name: Run Bundler
        run: yarn workspace example-apollo-federation-compatibility build
      - name: Apollo Federation Subgraph Compatibility
        uses: apollographql/federation-subgraph-compatibility@v2
        with:
          workingDirectory: examples/v1-next/apollo-federation-compatibility
          compose: docker-compose.yaml
          schema: schema.graphql
          path: /graphql
          token: ${{ secrets.GITHUB_TOKEN }}
          failOnWarning: true
          failOnRequired: true
          debug: true
